language: ruby

services:
  - postgresql

rvm:
    - 2.3.0

env:
    - RAILS_ENV=test

before_script:
    # - psql -c 'drop database if exists slopespot_test;' -U postgres
    # - psql -c 'create database slopespot_test;' -U postgres
    - bundle exec rails db:reset
    - bundle exec rails db:migrate