default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: action_cable_chat_app_dev

test:
  <<: *default
  database: action_cable_chat_app_test

production:
  <<: *default
  database: action_cable_chat_app_production
